// gallery.js
$("body").find("#a0").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a0").attr("alt", "???");
$("body").find("#a1").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a1").attr("alt", "???");
$("body").find("#a2").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a2").attr("alt", "???");
$("body").find("#a3").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a3").attr("alt", "???");
$("body").find("#a4").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a4").attr("alt", "???");
$("body").find("#a5").css("background-image", "url('assets/gallerymystery.jpg')");
$("body").find("#a5").attr("alt", "???");
